'use strict';
const KEY='pauza.entries.v1';
const $=id=>document.getElementById(id);
const reasons=[...document.querySelectorAll('.reason')];
let selected=null;
function readEntries(){const value=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(value))throw new Error('Invalid data');return value.filter(x=>x&&typeof x.date==='string'&&typeof x.note==='string'&&typeof x.reason==='string');}
function show(id){for(const view of ['entry-view','analysis-view','success-view'])$(view).hidden=view!==id;window.scrollTo({top:0,behavior:'instant'});}
function message(text){$('form-message').textContent=text;$('form-message').hidden=!text;}
reasons.forEach(button=>button.addEventListener('click',()=>{selected=selected===button.textContent?null:button.textContent;reasons.forEach(b=>b.setAttribute('aria-pressed',String(b.textContent===selected)));message('');}));
function save(reconsidered){const note=$('note').value.trim();if(!reconsidered&&!selected&&!note){message('Выбери причину или напиши пару слов.');$('note').focus();return;}try{const entries=readEntries();entries.push({id:crypto.randomUUID(),date:new Date().toISOString(),reason:selected||'',note,reconsidered});localStorage.setItem(KEY,JSON.stringify(entries));}catch{message('Не получилось сохранить запись в браузере. Проверь, разрешено ли хранение данных. Текст остался здесь.');return;}$('entry-form').reset();selected=null;reasons.forEach(b=>b.setAttribute('aria-pressed','false'));message('');$('success-title').textContent=reconsidered?'Пауза состоялась':'Запись сохранена';$('success-copy').textContent=reconsidered?'Ты решила не открывать ленту. Мы отметили это в твоих записях.':'Теперь можно продолжить свой день. Эта пауза уже есть в твоих записях.';show('success-view');$('success-title').focus();}
$('entry-form').addEventListener('submit',event=>{event.preventDefault();save(false);});$('reconsider').addEventListener('click',()=>save(true));
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function analysis(){show('analysis-view');$('summary').replaceChildren();$('history').replaceChildren();$('export').hidden=true;let entries;try{entries=readEntries();}catch{$('summary').append(element('p','Не удалось прочитать записи в этом браузере.'));return;}if(!entries.length){$('summary').append(element('p','Пока здесь пусто. Сохрани первую паузу — здесь появятся твои причины и записи.'));return;}$('export').hidden=false;const stats=element('div',undefined,'stats');for(const [value,label]of[[entries.length,'всего пауз'],[entries.filter(e=>e.reconsidered).length,'передумала открывать']]){const block=element('div');block.append(element('strong',value),element('span',label));stats.append(block);}$('summary').append(stats);const counts=new Map();for(const entry of entries){const reason=entry.reason||'Своя заметка';counts.set(reason,(counts.get(reason)||0)+1);}const distribution=element('div',undefined,'distribution');for(const[reason,count]of[...counts].sort((a,b)=>b[1]-a[1])){const line=element('p');line.append(element('span',reason),element('span',`${count}`));const bar=element('div',undefined,'bar');const fill=element('i');fill.style.width=`${count/entries.length*100}%`;bar.append(fill);distribution.append(line,bar);}$('summary').append(distribution);for(const entry of [...entries].reverse()){const card=element('article',undefined,'entry');const date=new Date(entry.date);const time=element('time',Number.isNaN(date.getTime())?'Дата неизвестна':date.toLocaleString('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}));card.append(time,element('h2',entry.reason||'Своя заметка'));if(entry.note)card.append(element('p',entry.note));if(entry.reconsidered)card.append(element('p','Передумала открывать','outcome'));$('history').append(card);}}
$('open-analysis').addEventListener('click',analysis);$('see-analysis').addEventListener('click',analysis);$('back').addEventListener('click',()=>show('entry-view'));$('again').addEventListener('click',()=>show('entry-view'));document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();show('entry-view');});
$('export').addEventListener('click',()=>{try{const blob=new Blob([JSON.stringify(readEntries(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`pauza-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{$('summary').prepend(element('p','Не удалось скачать записи. Попробуй ещё раз.'));}});
